title: Project

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            label: Project description
            help: Simple description of [project](https://poop.com)
            type: textarea
          client:
            icon: user
            type: text
            width: 1/2
            required: true
            maxlength: 10
          year:
            before: Finished
            type: number
            width: 1/2
          category:
            type: select
            options:
              - Fashion
              - Motoring
              - Web Design
            width: 1/2
          link:
            after: url
            type: url
            width: 1/2
          tags:
            type: tags
  sidebar:
    width: 1/3
    sections:
      files:
        type: files
        layout: cards
        image:
          ratio: 1/1
        template: gallery-image
